# Wiki name
site_name: CBuild wiki

# CBuild repository
repo_url: https://gitlab.com/cbuild/cbuild
repo_name: "CBuild"
edit_uri: edit/master/doxygen/wiki/docs/

# About wiki
site_description: 'Wiki for CBuild build system for c++'
site_author: 'WolodiaM'
copyright: 'GFDL-1.3-or-later'

# More warnings (and some removed ;) )
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
  not_found: ignore # We have Doxygen links that alwayl will be undefined

# Wiki theme
theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true
  hljs_languages:
    - cpp
    - c
    - bash
    - sh
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

extra_css:
  - style/font.css

# Build directories
docs_dir: wiki/mkdocs/docs/
site_dir: wiki/mkdocs/site/

# Extensions
markdown_extensions:
  - nl2br
  - smarty

# Navigation bar
nav:
  - 'Home': 'index.md'
  - 'Doxygen documentation': 'doxygen/index.html'
  - 'License':
    - 'Wiki License': 'https://www.gnu.org/licenses/fdl-1.3.html'
    - 'Code License': 'https://www.gnu.org/licenses/gpl-3.0.html'
  - 'Info':
    - 'Project information': 'info/info.md'
    - 'Usage': 'info/usage.md'
  - 'Internals':
    - 'CBuild internals': 'internals/internal_cbuild_structure.md'
  - 'Usage':
    - 'Creating buildscript': 'usage/buildscript.md'
