name: Build wiki for Wolodiam/CBuild
run-name: ${{ github.actor }} building wiki for Wolodiam/CBuild
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    name: Build wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq build-essential doxygen pandoc
      - name: Build wiki
        run: |
          gcc cbuild.c -o cbuild.run
          ./cbuild.run docs wikimk
          ./cbuild.run docs wiki
          ./cbuild.run docs doxygen
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./wiki/out
  deploy:
    name: Deploy wiki
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy wiki to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4